/* NoxOS - tables de chaines FR / EN (voir include/nox/lang.h)
 * Les accents sont en Latin-1 (\xE9 = e accent aigu...), l'encodage de la
 * police 8x16 du kernel. */
#include <nox/lang.h>

static enum lang current = LANG_FR;

static const char *const strings[LANG_COUNT][STR_COUNT] = {
    [LANG_FR] = {
        [STR_MENU]           = "Menu",
        [STR_EXPLORER]       = "Explorateur",
        [STR_TERMINAL]       = "Terminal",
        [STR_SETTINGS]       = "Param\xE8tres",
        [STR_TASKMGR]        = "Gestionnaire des t\xE2" "ches",
        [STR_ABOUT]          = "\xC0 propos de NoxOS",
        [STR_SHUTDOWN]       = "Arr\xEAter",
        [STR_REBOOT]         = "Red\xE9marrer",
        [STR_APPS]           = "Applications",
        [STR_SYSTEM]         = "Syst\xE8me",
        [STR_CLOSE]          = "Fermer",
        [STR_HOME]           = "Accueil",
        [STR_COMPUTER]       = "Ordinateur",
        [STR_DOCUMENTS]      = "Documents",
        [STR_IMAGES]         = "Images",
        [STR_MUSIC]          = "Musique",
        [STR_VIDEOS]         = "Vid\xE9os",
        [STR_DOWNLOADS]      = "T\xE9l\xE9" "chargements",
        [STR_FOLDER]         = "Dossier",
        [STR_FILE]           = "Fichier",
        [STR_ITEMS]          = "\xE9l\xE9ment(s)",
        [STR_EMPTY_FOLDER]   = "Ce dossier est vide.",
        [STR_NO_DISK]        = "Aucun volume NoxFS mont\xE9.",
        [STR_NEW_FOLDER]     = "Nouveau dossier",
        [STR_READ_ONLY_HINT] = "NoxFS est en lecture seule (\xE9" "criture pr\xE9vue en v0.6)",
        [STR_LANGUAGE]       = "Langue",
        [STR_FRENCH]         = "Fran\xE7" "ais",
        [STR_ENGLISH]        = "Anglais",
        [STR_TASKBAR]        = "Barre des t\xE2" "ches",
        [STR_TASKBAR_POS]    = "Position",
        [STR_BOTTOM]         = "En bas",
        [STR_TOP]            = "En haut",
        [STR_TASKBAR_ALIGN]  = "Alignement",
        [STR_CENTER]         = "Centr\xE9",
        [STR_LEFT]           = "\xC0 gauche",
        [STR_SHOW_CLOCK]     = "Afficher l'horloge",
        [STR_YES]            = "Oui",
        [STR_NO]             = "Non",
        [STR_PRIVACY]        = "Confidentialit\xE9",
        [STR_PRIVACY_TEXT]   = "Aucune t\xE9l\xE9m\xE9trie, aucun identifiant machine.",
        [STR_ABOUT_TEXT1]    = "Syst\xE8me d'exploitation \xE9" "crit de z\xE9ro.",
        [STR_ABOUT_TEXT2]    = "Noyau, pilotes, NoxFS et bureau : code NoxOS.",
        [STR_ABOUT_TEXT3]    = "Aucune base Linux.",
        [STR_TM_HEADER]      = " ID  \xC9tat       CPU(ms)  Mode    Nom",
        [STR_TM_THREADS]     = "Threads",
        [STR_TM_MEMORY]      = "M\xE9moire",
        [STR_TM_UPTIME]      = "Allum\xE9 depuis",
        [STR_STATE_READY]    = "pr\xEAt",
        [STR_STATE_RUNNING]  = "en cours",
        [STR_STATE_SLEEPING] = "endormi",
        [STR_STATE_ZOMBIE]   = "termin\xE9",
        [STR_KERNEL]         = "noyau",
        [STR_USER]           = "utilis.",
        [STR_TERMINAL_HINT]  = "Terminal NoxOS - tapez 'help'",
        [STR_TEXT_VIEWER]    = "Lecteur de texte",
        [STR_WALLPAPER]      = "Fond d'\xE9" "cran",
        [STR_WALLPAPER_AUTO] = "Change \xE0 chaque d\xE9marrage",
        [STR_WP_NIGHT]       = "Nox",
        [STR_WP_AURORA]      = "N\xE9on",
        [STR_WP_FOREST]      = "Anime",
        [STR_VERSION]        = "Version",
        [STR_LINES]          = "lignes",
        [STR_SCROLL_HINT]    = "Molette ou touches j/k pour d\xE9" "filer",
    },
    [LANG_EN] = {
        [STR_MENU]           = "Menu",
        [STR_EXPLORER]       = "Files",
        [STR_TERMINAL]       = "Terminal",
        [STR_SETTINGS]       = "Settings",
        [STR_TASKMGR]        = "Task Manager",
        [STR_ABOUT]          = "About NoxOS",
        [STR_SHUTDOWN]       = "Shut down",
        [STR_REBOOT]         = "Restart",
        [STR_APPS]           = "Applications",
        [STR_SYSTEM]         = "System",
        [STR_CLOSE]          = "Close",
        [STR_HOME]           = "Home",
        [STR_COMPUTER]       = "Computer",
        [STR_DOCUMENTS]      = "Documents",
        [STR_IMAGES]         = "Pictures",
        [STR_MUSIC]          = "Music",
        [STR_VIDEOS]         = "Videos",
        [STR_DOWNLOADS]      = "Downloads",
        [STR_FOLDER]         = "Folder",
        [STR_FILE]           = "File",
        [STR_ITEMS]          = "item(s)",
        [STR_EMPTY_FOLDER]   = "This folder is empty.",
        [STR_NO_DISK]        = "No NoxFS volume mounted.",
        [STR_NEW_FOLDER]     = "New folder",
        [STR_READ_ONLY_HINT] = "NoxFS is read-only (write support planned for v0.6)",
        [STR_LANGUAGE]       = "Language",
        [STR_FRENCH]         = "French",
        [STR_ENGLISH]        = "English",
        [STR_TASKBAR]        = "Taskbar",
        [STR_TASKBAR_POS]    = "Position",
        [STR_BOTTOM]         = "Bottom",
        [STR_TOP]            = "Top",
        [STR_TASKBAR_ALIGN]  = "Alignment",
        [STR_CENTER]         = "Center",
        [STR_LEFT]           = "Left",
        [STR_SHOW_CLOCK]     = "Show clock",
        [STR_YES]            = "Yes",
        [STR_NO]             = "No",
        [STR_PRIVACY]        = "Privacy",
        [STR_PRIVACY_TEXT]   = "No telemetry, no machine identifier.",
        [STR_ABOUT_TEXT1]    = "Operating system written from scratch.",
        [STR_ABOUT_TEXT2]    = "Kernel, drivers, NoxFS and desktop: NoxOS code.",
        [STR_ABOUT_TEXT3]    = "No Linux base.",
        [STR_TM_HEADER]      = " ID  State      CPU(ms)  Mode    Name",
        [STR_TM_THREADS]     = "Threads",
        [STR_TM_MEMORY]      = "Memory",
        [STR_TM_UPTIME]      = "Uptime",
        [STR_STATE_READY]    = "ready",
        [STR_STATE_RUNNING]  = "running",
        [STR_STATE_SLEEPING] = "sleeping",
        [STR_STATE_ZOMBIE]   = "finished",
        [STR_KERNEL]         = "kernel",
        [STR_USER]           = "user",
        [STR_TERMINAL_HINT]  = "NoxOS Terminal - type 'help'",
        [STR_TEXT_VIEWER]    = "Text viewer",
        [STR_WALLPAPER]      = "Wallpaper",
        [STR_WALLPAPER_AUTO] = "Changes on every boot",
        [STR_WP_NIGHT]       = "Nox",
        [STR_WP_AURORA]      = "Neon",
        [STR_WP_FOREST]      = "Anime",
        [STR_VERSION]        = "Version",
        [STR_LINES]          = "lines",
        [STR_SCROLL_HINT]    = "Wheel or j/k keys to scroll",
    },
};

void lang_set(enum lang l)
{
    if (l < LANG_COUNT)
        current = l;
}

enum lang lang_get(void) { return current; }

const char *L(enum str_id id)
{
    if (id >= STR_COUNT)
        return "?";
    const char *s = strings[current][id];
    return s ? s : strings[LANG_FR][id];
}
