[Icon Theme]
Name=Nox
Comment=Pictogrammes Nox OS (base Lucide, ISC)
Inherits=breeze-dark,hicolor
Directories=scalable/apps,scalable/actions,scalable/status,scalable/devices,scalable/places,scalable/categories

[scalable/apps]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Apps

[scalable/actions]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Actions

[scalable/status]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Status

[scalable/devices]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Devices

[scalable/places]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Places

[scalable/categories]
Size=48
MinSize=8
MaxSize=512
Type=Scalable
Context=Categories
