/**
 * Commercial settings for Fox Media. Everything here is public: never put a
 * private key or a payment secret in this file.
 */

/** Price of one lifetime key, in euros. Raise it when you want. */
export const PRICE_EUR = Number(import.meta.env.VITE_PRICE_EUR ?? 1);

/** The first installs get a free "founder" key from the licence server. */
export const FREE_INSTALLS = Number(import.meta.env.VITE_FREE_INSTALLS ?? 100);

/**
 * Fox Media is free: the whole app stays unlocked, with no key, no trial and no
 * network call. Set VITE_FREE_MODE=0 to bring the licence gate back.
 */
export const FREE_MODE = (import.meta.env.VITE_FREE_MODE ?? '1') !== '0';

/** Days of full access before a key is required. */
export const TRIAL_DAYS = Number(import.meta.env.VITE_TRIAL_DAYS ?? 7);

/** Media items allowed during the trial. */
export const TRIAL_ITEM_LIMIT = Number(import.meta.env.VITE_TRIAL_ITEM_LIMIT ?? 20);

/** Licence server issuing signed keys (also serves the free founder keys). */
export const LICENCE_SERVER = import.meta.env.VITE_LICENCE_SERVER ?? '';

/**
 * Ad-free plans. The app itself is free with ads: paying only removes them.
 * `months: 0` means forever. Prices are in euros.
 */
export const NOADS_PLANS: { id: string; label: string; months: number; price: number }[] = [
  { id: 'month', label: '1 mois sans pub', months: 1, price: 1 },
  { id: 'two-months', label: '2 mois sans pub', months: 2, price: 5 },
  { id: 'lifetime', label: 'À vie, sans pub', months: 0, price: 100 },
];

/** Payment page (Stripe Payment Link or PayPal button) opened to buy a key. */
export const CHECKOUT_URL = import.meta.env.VITE_CHECKOUT_URL ?? '';

/**
 * Base64 SPKI of the ECDSA P-256 public key matching the licence server's
 * private key. Generated by `npm run licence:keys`.
 */
export const LICENCE_PUBLIC_KEY = import.meta.env.VITE_LICENCE_PUBLIC_KEY ?? '';

/** Public landing page, used for share and referral links. */
export const SHARE_URL = import.meta.env.VITE_SHARE_URL ?? 'https://fox-media.app';

/** Referrals allowed per user; each referred friend gets a free key. */
export const REFERRAL_LIMIT = Number(import.meta.env.VITE_REFERRAL_LIMIT ?? 5);

/** Google OAuth client id, needed only for the optional Drive backup. */
export const GOOGLE_CLIENT_ID = import.meta.env.VITE_GOOGLE_CLIENT_ID ?? '';

/**
 * AdSense publisher id (`ca-pub-…`) and slot used for the banner shown to
 * users without a licence. Empty means no ad is rendered at all.
 */
export const ADS_CLIENT = import.meta.env.VITE_ADS_CLIENT ?? '';
export const ADS_SLOT = import.meta.env.VITE_ADS_SLOT ?? '';

/**
 * Alternative to AdSense: URL of the invoke/banner script given by another ad
 * network (Adsterra, Monetag, A-ADS…). Injected as-is inside the banner slot.
 */
export const ADS_SCRIPT = import.meta.env.VITE_ADS_SCRIPT ?? '';

/** Address shown on the house banner while no ad network is configured. */
export const ADS_CONTACT = import.meta.env.VITE_ADS_CONTACT ?? 'foxmedia.pub@hotmail.com';

/**
 * Sponsor plans sold directly to advertisers, cheaper per month as the
 * duration grows. Prices are in euros and only used for display.
 */
export const ADS_PLANS: { months: number; price: number }[] = [
  { months: 1, price: 5 },
  { months: 2, price: 9 },
  { months: 3, price: 12 },
  { months: 6, price: 20 },
  { months: 12, price: 35 },
];

/**
 * Code opening the owner-only wallet screen. Change it with
 * VITE_OWNER_CODE before publishing so only you can open it.
 */
export const OWNER_CODE = import.meta.env.VITE_OWNER_CODE ?? 'fox-patron';

/** Payment link where advertisers pay you (PayPal.me or Stripe link). */
export const ADS_PAYMENT_URL = import.meta.env.VITE_ADS_PAYMENT_URL ?? '';

/**
 * MoneyFox payout link: your PayPal.me or Stripe page. It feeds the QR code
 * people scan to pay you and the "Retirer" shortcut.
 */
export const PAYOUT_URL = import.meta.env.VITE_PAYOUT_URL ?? '';
